import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Montserrat } from "next/font/google";
import TopNavbar from "@/components/navigation/top-navbar";
import "./globals.css";
import ClientWrapper from "@/components/client-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-poppins',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: "Recommetra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${poppins.className} ${montserrat.className} antialiased font-[family-name:var(--font-montserrat)] bg-background dark min-h-screen scrollbar-hide`}>

        {/* Background Gradient */}
        {/* <div className="fixed top-0 left-0 w-full h-full -z-50 bg-animated-glow blur-3xl"></div> */}
        <div className="fixed inset-0 -z-50">
          <div className="absolute inset-0">
            <div
              className="absolute md:-top-1/3 top-0 left-0 md:w-[1024px] md:h-[1024px] w-72 h-72 bg-gradient-to-br from-primary to-background rounded-full mix-blend-multiply filter blur-[128px] opacity-40 md:opacity-15"></div>
            <div
              className="absolute md:-bottom-1/3 -bottom-40 -right-36 md:w-[360px] md:h-[360px] w-72 h-72 bg-gradient-to-br from-primary to-background rounded-full mix-blend-multiply filter blur-[128px] opacity-20 md:opacity-15 md:hidden"></div>
          </div>
        </div>

        {/* Main Content */}
        <TopNavbar />
        <ClientWrapper>
          {children}
        </ClientWrapper>
      </body>
    </html>
  );
}
