import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import TopNavbar from "@/components/navigation/top-navbar";
import "./globals.css";
import ClientWrapper from "@/components/client-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Recommetra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased font-[family-name:var(--font-geist-sans)] bg-pattern-2 dark min-h-screen scrollbar-hide`}>
        <TopNavbar />
        <ClientWrapper>
          {children}
        </ClientWrapper>
      </body>
    </html>
  );
}
